# Generated by Django 4.1 on 2022-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
